language: node_js
sudo: required
node_js:
  - 10
cache:
  directories:
    - node_modules

branches:
  only:
    - master

git:
  clone: false

before_install:
  - git clone --depth=50 --branch=master https://github.com/upcwangying/myblog.git upcwangying/myblog
  - cd upcwangying/myblog && sed -i "s/upcwangying.//g" ./.gitmodules && git submodule update --init --recursive
  - yarn global add hexo-cli

install:
  - yarn install

script:
  - hexo clean && hexo g && gulp
  - cd ./public && touch CNAME && echo 'upcwangying.com' > CNAME && cd ..

deploy:
  provider: pages
  repo: upcwangying/upcwangying.github.io
  target_branch: master
  email: upcwangying@126.com
  name: upcwangying
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  local_dir: public
